name: development

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  sample-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World"
